### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Zumbalamambo** [introlab/rtabmap#545] opened 2020-05-08 08:32 UTC
I'm trying to install rtabmap in Ubuntu 18.+

I'm getting the following error,
```

corelib/src/Features2d.cpp:916:19: error: incomplete type ‘CV_SIFT {aka cv::xfeatures2d::SIFT}’ used in nested name specifier
  _sift = CV_SIFT::create(this->getMaxFeatures(), nOctaveLayers_, contrastThreshold_, edgeThreshold_, sigma_);
```

**Comment by Zumbalamambo** [comment] 2020-05-08 08:33
I have installed opencv 4.3 with contrib module by the way. and I'm trying to install the latest release of rtabmap

**Comment by matlabbe** [comment] 2020-05-09 15:09
Duplicate of https://github.com/introlab/rtabmap/issues/538

**Closed by matlabbe** 2020-05-09 15:09 UTC
