### ISSUE TITLE
export point cloud map automatically

### ISSUE THREAD

**Issue by wangwayjay** [introlab/rtabmap#620] opened 2020-10-26 03:11 UTC
Hello Mathieu
I would like to export point cloud map every five seconds when the rtabmap is running. Could you help me achieve this goal please? Thank you very much.

**Comment by matlabbe** [comment] 2020-11-06 21:01
Duplicate of http://official-rtab-map-forum.67519.x6.nabble.com/export-point-cloud-map-automatically-td7108.html#a7147

**Closed by matlabbe** 2020-11-06 21:01 UTC
