### ISSUE TITLE
rtabmap is not publishing map frame 

### ISSUE THREAD

**Issue by hariharan382** [introlab/rtabmap#880] opened 2022-07-16 08:06 UTC
Hi I am trying to implement rtabmap in gazebo with d435 plugin , but I am getting as follows error

[FATAL] (2022-07-16 13:26:27.179) Memory.cpp:4387::createSignature() Condition (data.depthOrRightRaw().empty() || ( ( data.depthOrRightRaw().type() == CV_16UC1 || data.depthOrRightRaw().type() == CV_32FC1 || data.depthOrRightRaw().type() == CV_8UC1) && ( (data.imageRaw().empty() && data.depthOrRightRaw().type() != CV_8UC1) || (data.depthOrRightRaw().rows <= data.imageRaw().rows && data.depthOrRightRaw().cols <= data.imageRaw().cols)))) not met! [image=(640/480, type=16, [accepted=0,16]) depth=(1280/720, type=2 [accepted=2(depth mm),5(depth m),0(stereo)]). For stereo, left and right images should be same size. For RGB-D, depth can be X times smaller than RGB (where X is an integer).]

**Comment by matlabbe** [comment] 2022-07-27 14:43
Duplicate of https://github.com/introlab/rtabmap_ros/issues/785

**Closed by matlabbe** 2022-07-27 14:43 UTC
