### ISSUE TITLE
using rtabmap standalone library with 2cameras

### ISSUE THREAD

**Issue by Nimaro76** [introlab/rtabmap#1100] opened 2023-07-26 18:51 UTC
Hello, 
I have a question that I would appreciate it if you could answer. can I use 2 cameras with RTABMAP standalone library to reconstruct the map of the environment? 
thank you in advance for answering this question.

**Comment by matlabbe** [comment] 2023-07-30 23:25
Duplicate of http://official-rtab-map-forum.206.s1.nabble.com/using-Standalone-RTABMAP-library-with-2-realsense-cameras-td9582.html#a9587

> Not with the standalone. You would have to use [rtabmap_ros](http://wiki.ros.org/rtabmap_ros) for this.

**Closed by matlabbe** 2023-07-30 23:25 UTC
